### ISSUE TITLE
use of expired token

### ISSUE THREAD

**Issue by shaan100** [rrd108/api-token-authenticator#9]
in my user table there is token_expiration field and token field so when user login then token generated by 

```php
private function generateToken(int $length = 36, string $expiration = '+6 hours')
{
  $random = base64_encode(Security::randomBytes($length));
  $cleaned = preg_replace('/[^A-Za-z0-9]/', '', $random);
  return [$cleaned, strtotime($expiration)];
}
```

and saved into users table in token field with token_expiration time but plugin does not prevent access data if toke expire so please give me solution how does it work?

**Comment by rrd108** [comment]
First you should check what token_expiration value is set in your database when the user logs in. 

The plugin checks if the token did not expired (https://github.com/rrd108/api-token-authenticator/blob/e3c8e7d737d92977da337f5fb8cb929d5140ce44/src/Authentication/Authenticator/ProvisoryTokenAuthenticator.php#L29) and give you an error message.

**Comment by rrd108** [comment]
Well it seems you are right, I should fix the issue.

**Comment by rrd108** [comment]
I added a test and it passes. 
So it seems something is missing from your code.

**Comment by shaan100** [comment]
![Screenshot from 2024-03-03 21-43-45](https://github.com/rrd108/api-token-authenticator/assets/105695000/6571a7d7-fee6-4fce-9de1-1b522adae8ad)
Application.php


UsersController.php login method

![Screenshot from 2024-03-03 21-44-30](https://github.com/rrd108/api-token-authenticator/assets/105695000/30cf93e5-29b6-47d1-b87e-297a60800d9d)


whats going wrong here? plugin does not check token expire time

**Comment by shaan100** [comment]
> I added a test and it passes. So it seems something is missing from your code.
think plugin does not check token

**Comment by rrd108** [comment]
can you share your `/config/apiTokenAuthenticator.php` file also?

**Comment by shaan100** [comment]
> can you share your `/config/apiTokenAuthenticator.php` file also?

nope! i do't create apiTokenAuthenticator.php because i am following the default convention as plugin mention in docs... like In users table must be token and token_expiration column but if users table different field name then need to create apiTokenAuthenticator.php file in /config directory! May I Right or Not?

**Comment by rrd108** [comment]
Ok, so that is the part you are missing.

You should do the folowwing steps:

- Remove `loadIdentifier` and `loadAuthenticator` parts from your `Application.php` file. You do not have to add any of these, the plugin handle these. In the `Application.php` file you just have to disable CSRF as mentioned here Disable CSRF protection
- As you use `token_expiration` you *should* have your own `config/apiTokenAuthenticator.php` file with the following content.

```php
<?php

return [
    'ApiTokenAuthenticator' => [
        'header' => 'Authorization',
        'tokenExpiration' => 'token_expiration',
    ]
];
```

This will do 2 things.
1. enable token expiration checks
2. Set the header for authentication as `Authorization`. By default the plugin watching a header named `Token`, but as I see you use `Authorization` instead of the default.

In the same time there is a problem. If you want to use `Bearer` it goes to the `value` od the token, not into the name. Because of this the check will fail.

You have 2 options:
1. Use a different authentication header. For example if you can use `Token` as the authorization header it will be handled automatically by the plugin.
2. If you want I can add support for `Bearer`

**Comment by rrd108** [comment]
I just tagged a new relase where the use of `Bearer` is more clear as using `prefix` was not documented yet.

**Comment by shaan100** [comment]
> 2\. Authorization

step 1 :-
As you said sir, I Removed loadIdentifier and loadAuthenticator parts from your Application.php file so now My Api stop to work because cakephp 5  Authentication(3.X) plugin recommended to add loadIdentifier and loadAuthenticator if token based access system developed.

step 2 
So As you said as the Authorization Header.. but there is already Authorization header 
`
$service->loadAuthenticator('Authentication.Token', [
                'queryParam' => 'token',
                'header' => 'Authorization',
                'tokenPrefix' => 'Token'
            ]);
`
I replace Bearer to Token again but the result are same now plugin does not check token expire or not even I created apiTokenAuthenticator.php file into config folder..

And please Add the support for Bearer, because it really necessary when developer use React or Vuejs then token send through Bearer so please Add on support for Bearer.

And Sir your plugin is really Awesome..

**Comment by shaan100** [comment]
> I just tagged a new relase where the use of `Bearer` is more clear as using `prefix` was not documented yet.

:+1:

**Comment by shaan100** [comment]
> > I Removed loadIdentifier and loadAuthenticator parts from your Application.php file so now My Api stop to work because cakephp 5  Authentication(3.X) plugin recommended to add loadIdentifier and loadAuthenticator if token based access system developed.
> 
> Yes, you are totally right, but if you use this plugin it does it for you. You do not have to add anything by yourself.
> 
> > So As you said as the Authorization Header.. but there is already Authorization header
> > Check my answer about. I hope it clarify.
> 
> The main thing is your `config/apiTokenAuthenticator.php` file. There you can set anything you want and the plugin should handle them well.

please share me example or code!! how can I handle this thing from config/apiTokenAuthenticator.php

**Comment by shaan100** [comment]
> Ok so first we should clarify a few things. What is the name of the token header you send to your API?

http://localhost:8765/api/users/view.json?token=g1UBEpFcJzz5JaSo1zkOKEvb9Trkt3XoFvrAIHRFjNqMWwXJ

config/apiTokenAuthenticator.php
`return [
    'ApiTokenAuthenticator' => [
        'header' => 'Authorization',
        'tokenExpiration' => 'token_expiration',
    ]
];
`

**Comment by rrd108** [comment]
Wait the axmpla you linked sends the tone is the url, not in a header. Is it what you want?

**Comment by rrd108** [comment]
It is up to you how you send the token.
If you do not have to adjust yourself to others I would recommend the following: 

From the screenshot I think you use Postman for testing.
1. Do not use this `Authorization` tab at all, remove what you have here.
2. On the `Headers` tab add a new Header with the name `Token` and with the value you have here in your example.

In this case your `config/apiTokenAuthenticator.php` should be this:

```php
<?php
return [ 'ApiTokenAuthenticator' => ['tokenExpiration' => 'token_expiration', ] ]; 
```

**Comment by shaan100** [comment]
> It is up to you how you send the token. If you do not have to adjust yourself to others I would recommend the following:
> 
> From the screenshot I think you use Postman for testing.
> 
> 1. Do not use this `Authorization` tab at all, remove what you have here.
> 2. On the `Headers` tab add a new Header with the name `Token` and with the value you have here in your example.
> 
> In this case your `config/apiTokenAuthenticator.php` should be this:
> 
> ```
> <?php
> return [ 'ApiTokenAuthenticator' => ['tokenExpiration' => 'token_expiration', ] ]; 
> ```

ok i will try it, but if i am using query string parameter like ?token=oklkdk032okej-0j23 so then plugin handle it or not? please add on this functioning in your plugin..

Thanks 
I will test it tomorrow

**Comment by rrd108** [comment]
Currently the plugin does *not* support query string parameters, onyle *headers*

**Comment by shaan100** [comment]
still its not working sir, i think plugin does not care about token expire or not

**Comment by rrd108** [comment]
I can confirm that the plugin checks token expiration.

So please share your `config/apiTokenAuthenticator.php` here.

Then try to log in and share details how you try to login. Also I need to see if you get any errors in your error log.

**Comment by shaan100** [comment]
![Uploading Screenshot from 2024-03-06 12-49-12.png…]()

**Comment by shaan100** [comment]
![Screenshot from 2024-03-06 12-49-12](https://github.com/rrd108/api-token-authenticator/assets/105695000/da2a109c-6487-472b-8a59-78b645d41d48)

**Comment by rrd108** [comment]
continued at #11
